/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PatientInfoRouteImport } from './routes/patient-info'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedStaffAppointmentsRouteImport } from './routes/_authenticated/staff.appointments'
import { Route as AuthenticatedPortalProfileRouteImport } from './routes/_authenticated/portal.profile'
import { Route as AuthenticatedPortalPrescriptionsRouteImport } from './routes/_authenticated/portal.prescriptions'
import { Route as AuthenticatedPortalLabResultsRouteImport } from './routes/_authenticated/portal.lab-results'
import { Route as AuthenticatedPortalInvoicesRouteImport } from './routes/_authenticated/portal.invoices'
import { Route as AuthenticatedPortalHistoryRouteImport } from './routes/_authenticated/portal.history'
import { Route as AuthenticatedPortalAppointmentsRouteImport } from './routes/_authenticated/portal.appointments'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientInfoRoute = PatientInfoRouteImport.update({
  id: '/patient-info',
  path: '/patient-info',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedStaffAppointmentsRoute =
  AuthenticatedStaffAppointmentsRouteImport.update({
    id: '/staff/appointments',
    path: '/staff/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalProfileRoute =
  AuthenticatedPortalProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalPrescriptionsRoute =
  AuthenticatedPortalPrescriptionsRouteImport.update({
    id: '/prescriptions',
    path: '/prescriptions',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalLabResultsRoute =
  AuthenticatedPortalLabResultsRouteImport.update({
    id: '/lab-results',
    path: '/lab-results',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalInvoicesRoute =
  AuthenticatedPortalInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalHistoryRoute =
  AuthenticatedPortalHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalAppointmentsRoute =
  AuthenticatedPortalAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/patient-info': typeof PatientInfoRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/portal/appointments': typeof AuthenticatedPortalAppointmentsRoute
  '/portal/history': typeof AuthenticatedPortalHistoryRoute
  '/portal/invoices': typeof AuthenticatedPortalInvoicesRoute
  '/portal/lab-results': typeof AuthenticatedPortalLabResultsRoute
  '/portal/prescriptions': typeof AuthenticatedPortalPrescriptionsRoute
  '/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/staff/appointments': typeof AuthenticatedStaffAppointmentsRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/patient-info': typeof PatientInfoRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/portal/appointments': typeof AuthenticatedPortalAppointmentsRoute
  '/portal/history': typeof AuthenticatedPortalHistoryRoute
  '/portal/invoices': typeof AuthenticatedPortalInvoicesRoute
  '/portal/lab-results': typeof AuthenticatedPortalLabResultsRoute
  '/portal/prescriptions': typeof AuthenticatedPortalPrescriptionsRoute
  '/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/staff/appointments': typeof AuthenticatedStaffAppointmentsRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/patient-info': typeof PatientInfoRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/portal/appointments': typeof AuthenticatedPortalAppointmentsRoute
  '/_authenticated/portal/history': typeof AuthenticatedPortalHistoryRoute
  '/_authenticated/portal/invoices': typeof AuthenticatedPortalInvoicesRoute
  '/_authenticated/portal/lab-results': typeof AuthenticatedPortalLabResultsRoute
  '/_authenticated/portal/prescriptions': typeof AuthenticatedPortalPrescriptionsRoute
  '/_authenticated/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/_authenticated/staff/appointments': typeof AuthenticatedStaffAppointmentsRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appointments'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/doctors'
    | '/patient-info'
    | '/services'
    | '/sitemap.xml'
    | '/portal'
    | '/api/chat'
    | '/portal/appointments'
    | '/portal/history'
    | '/portal/invoices'
    | '/portal/lab-results'
    | '/portal/prescriptions'
    | '/portal/profile'
    | '/staff/appointments'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appointments'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/doctors'
    | '/patient-info'
    | '/services'
    | '/sitemap.xml'
    | '/api/chat'
    | '/portal/appointments'
    | '/portal/history'
    | '/portal/invoices'
    | '/portal/lab-results'
    | '/portal/prescriptions'
    | '/portal/profile'
    | '/staff/appointments'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/appointments'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/doctors'
    | '/patient-info'
    | '/services'
    | '/sitemap.xml'
    | '/_authenticated/portal'
    | '/api/chat'
    | '/_authenticated/portal/appointments'
    | '/_authenticated/portal/history'
    | '/_authenticated/portal/invoices'
    | '/_authenticated/portal/lab-results'
    | '/_authenticated/portal/prescriptions'
    | '/_authenticated/portal/profile'
    | '/_authenticated/staff/appointments'
    | '/_authenticated/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DoctorsRoute: typeof DoctorsRoute
  PatientInfoRoute: typeof PatientInfoRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-info': {
      id: '/patient-info'
      path: '/patient-info'
      fullPath: '/patient-info'
      preLoaderRoute: typeof PatientInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/staff/appointments': {
      id: '/_authenticated/staff/appointments'
      path: '/staff/appointments'
      fullPath: '/staff/appointments'
      preLoaderRoute: typeof AuthenticatedStaffAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/profile': {
      id: '/_authenticated/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof AuthenticatedPortalProfileRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/prescriptions': {
      id: '/_authenticated/portal/prescriptions'
      path: '/prescriptions'
      fullPath: '/portal/prescriptions'
      preLoaderRoute: typeof AuthenticatedPortalPrescriptionsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/lab-results': {
      id: '/_authenticated/portal/lab-results'
      path: '/lab-results'
      fullPath: '/portal/lab-results'
      preLoaderRoute: typeof AuthenticatedPortalLabResultsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/invoices': {
      id: '/_authenticated/portal/invoices'
      path: '/invoices'
      fullPath: '/portal/invoices'
      preLoaderRoute: typeof AuthenticatedPortalInvoicesRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/history': {
      id: '/_authenticated/portal/history'
      path: '/history'
      fullPath: '/portal/history'
      preLoaderRoute: typeof AuthenticatedPortalHistoryRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/appointments': {
      id: '/_authenticated/portal/appointments'
      path: '/appointments'
      fullPath: '/portal/appointments'
      preLoaderRoute: typeof AuthenticatedPortalAppointmentsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
  }
}

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalAppointmentsRoute: typeof AuthenticatedPortalAppointmentsRoute
  AuthenticatedPortalHistoryRoute: typeof AuthenticatedPortalHistoryRoute
  AuthenticatedPortalInvoicesRoute: typeof AuthenticatedPortalInvoicesRoute
  AuthenticatedPortalLabResultsRoute: typeof AuthenticatedPortalLabResultsRoute
  AuthenticatedPortalPrescriptionsRoute: typeof AuthenticatedPortalPrescriptionsRoute
  AuthenticatedPortalProfileRoute: typeof AuthenticatedPortalProfileRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalAppointmentsRoute: AuthenticatedPortalAppointmentsRoute,
  AuthenticatedPortalHistoryRoute: AuthenticatedPortalHistoryRoute,
  AuthenticatedPortalInvoicesRoute: AuthenticatedPortalInvoicesRoute,
  AuthenticatedPortalLabResultsRoute: AuthenticatedPortalLabResultsRoute,
  AuthenticatedPortalPrescriptionsRoute: AuthenticatedPortalPrescriptionsRoute,
  AuthenticatedPortalProfileRoute: AuthenticatedPortalProfileRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
  AuthenticatedStaffAppointmentsRoute: typeof AuthenticatedStaffAppointmentsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
  AuthenticatedStaffAppointmentsRoute: AuthenticatedStaffAppointmentsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AppointmentsRoute: AppointmentsRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DoctorsRoute: DoctorsRoute,
  PatientInfoRoute: PatientInfoRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
