/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PatientInfoRouteImport } from './routes/patient-info'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedStaffAppointmentsRouteImport } from './routes/_authenticated/staff.appointments'
import { Route as AuthenticatedPortalAppointmentsRouteImport } from './routes/_authenticated/portal.appointments'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientInfoRoute = PatientInfoRouteImport.update({
  id: '/patient-info',
  path: '/patient-info',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffAppointmentsRoute =
  AuthenticatedStaffAppointmentsRouteImport.update({
    id: '/staff/appointments',
    path: '/staff/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalAppointmentsRoute =
  AuthenticatedPortalAppointmentsRouteImport.update({
    id: '/portal/appointments',
    path: '/portal/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/patient-info': typeof PatientInfoRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/portal/appointments': typeof AuthenticatedPortalAppointmentsRoute
  '/staff/appointments': typeof AuthenticatedStaffAppointmentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/patient-info': typeof PatientInfoRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/portal/appointments': typeof AuthenticatedPortalAppointmentsRoute
  '/staff/appointments': typeof AuthenticatedStaffAppointmentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/patient-info': typeof PatientInfoRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/portal/appointments': typeof AuthenticatedPortalAppointmentsRoute
  '/_authenticated/staff/appointments': typeof AuthenticatedStaffAppointmentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appointments'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/doctors'
    | '/patient-info'
    | '/services'
    | '/sitemap.xml'
    | '/api/chat'
    | '/portal/appointments'
    | '/staff/appointments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appointments'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/doctors'
    | '/patient-info'
    | '/services'
    | '/sitemap.xml'
    | '/api/chat'
    | '/portal/appointments'
    | '/staff/appointments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/appointments'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/doctors'
    | '/patient-info'
    | '/services'
    | '/sitemap.xml'
    | '/api/chat'
    | '/_authenticated/portal/appointments'
    | '/_authenticated/staff/appointments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DoctorsRoute: typeof DoctorsRoute
  PatientInfoRoute: typeof PatientInfoRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-info': {
      id: '/patient-info'
      path: '/patient-info'
      fullPath: '/patient-info'
      preLoaderRoute: typeof PatientInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff/appointments': {
      id: '/_authenticated/staff/appointments'
      path: '/staff/appointments'
      fullPath: '/staff/appointments'
      preLoaderRoute: typeof AuthenticatedStaffAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/appointments': {
      id: '/_authenticated/portal/appointments'
      path: '/portal/appointments'
      fullPath: '/portal/appointments'
      preLoaderRoute: typeof AuthenticatedPortalAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortalAppointmentsRoute: typeof AuthenticatedPortalAppointmentsRoute
  AuthenticatedStaffAppointmentsRoute: typeof AuthenticatedStaffAppointmentsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortalAppointmentsRoute: AuthenticatedPortalAppointmentsRoute,
  AuthenticatedStaffAppointmentsRoute: AuthenticatedStaffAppointmentsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AppointmentsRoute: AppointmentsRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DoctorsRoute: DoctorsRoute,
  PatientInfoRoute: PatientInfoRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
